import = [
    "~/dotfiles/alacritty/themes/themes/seashells.toml",
]

#[colors.primary]
#background = "#000000"
#foreground = "#eaeaea"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 5
y = 5

